const countryListAlpha2 = {
  GB: "English",
  FR: "French",
  ES: "Spanish",
  CN: "Chinese",
  DE: "German",
  ZA: "Africaans",
  AL: "Albanian",
  DZ: "Algerian",
  SA: "Arab",
  AM: "Armenian",
  BD: "Bangladeshi",
  BG: "Bulgarian",
  KH: "Cambodian",
  HR: "Croatian",
  CZ: "Czech",
  DK: "Danish",
  NL: "Dutch",
  EE: "Estonian",
  FI: "Finnish",
  GR: "Greek",
  IL: "Hebrew",
  HU: "Hungarian",
  IN: "Indian",
  IT: "Italian",
  JP: "Japanese",
  KR: "Korean",
  LV: "Latvian",
  LT: "Lithuanian",
  MY: "Malaysian",
  MN: "Mongolian",
  NO: "Norwegian",
  PL: "Polish",
  BR: "Portuguese",
  RO: "Romanian",
  RU: "Russian",
  RS: "Serbian",
  SK: "Slovakian",
  SI: "Slovenian",
  SE: "Swedish",
  TH: "Thai",
  TR: "Turkish",
  VN: "Vietnamese",
}

export default countryListAlpha2
