// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bet struct {
	PlayerID string `json:"playerId"`
	Amount   int    `json:"amount"`
}

type BetInput struct {
	GameID   string `json:"gameId"`
	PlayerID string `json:"playerId"`
	Amount   int    `json:"amount"`
}

type BettingRound struct {
	QuestionRound   *QuestionRound `json:"questionRound"`
	Bets            []*Bet         `json:"bets"`
	CurrentPlayerID string         `json:"currentPlayerId"`
}

type Game struct {
	ID             string           `json:"id"`
	Players        []*Player        `json:"players"`
	QuestionRounds []*QuestionRound `json:"questionRounds"`
	DealerID       string           `json:"dealerId"`
}

type Guess struct {
	Guess    float64 `json:"guess"`
	PlayerID string  `json:"playerId"`
}

type GuessInput struct {
	GameID   string  `json:"gameId"`
	PlayerID string  `json:"playerId"`
	Guess    float64 `json:"guess"`
}

type Player struct {
	ID    string `json:"id"`
	Money int    `json:"money"`
	Game  *Game  `json:"game"`
}

type Question struct {
	ID       string   `json:"id"`
	Question string   `json:"question"`
	Answer   float64  `json:"answer"`
	Hints    []string `json:"hints"`
}

type QuestionRound struct {
	Game            *Game           `json:"game"`
	Question        *Question       `json:"question"`
	Guesses         []*Guess        `json:"guesses"`
	BettingRounds   []*BettingRound `json:"bettingRounds"`
	FoldedPlayerIds []string        `json:"foldedPlayerIds"`
}
