// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bet struct {
	PlayerID string `json:"playerId"`
	Amount   int    `json:"amount"`
}

type BetInput struct {
	GameID          string `json:"gameId"`
	QuestionRoundID string `json:"questionRoundId"`
	BettingRoundID  string `json:"bettingRoundId"`
	PlayerID        string `json:"playerId"`
	Amount          int    `json:"amount"`
}

type BettingRound struct {
	ID                 string         `json:"id"`
	QuestionRound      *QuestionRound `json:"questionRound"`
	Bets               []*Bet         `json:"bets"`
	CurrentPlayerID    string         `json:"currentPlayerId"`
	LastRaisedPlayerID string         `json:"lastRaisedPlayerId"`
}

type Game struct {
	ID                   string           `json:"id"`
	Players              []*Player        `json:"players"`
	QuestionRounds       []*QuestionRound `json:"questionRounds"`
	CurrentQuestionRound int              `json:"currentQuestionRound"`
	DealerID             string           `json:"dealerId"`
}

type Guess struct {
	Guess    float64 `json:"guess"`
	PlayerID string  `json:"playerId"`
}

type GuessInput struct {
	GameID   string  `json:"gameId"`
	PlayerID string  `json:"playerId"`
	Guess    float64 `json:"guess"`
}

type Player struct {
	ID    string `json:"id"`
	Money int    `json:"money"`
}

type Question struct {
	ID       string   `json:"id"`
	Question string   `json:"question"`
	Answer   float64  `json:"answer"`
	Hints    []string `json:"hints"`
}

type QuestionRound struct {
	ID                  string          `json:"id"`
	Game                *Game           `json:"game"`
	Question            *Question       `json:"question"`
	Guesses             []*Guess        `json:"guesses"`
	BettingRounds       []*BettingRound `json:"bettingRounds"`
	CurrentBettingRound int             `json:"currentBettingRound"`
	FoldedPlayerIds     []string        `json:"foldedPlayerIds"`
}
