// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bet struct {
	PlayerID string `json:"playerId"`
	Amount   int    `json:"amount"`
}

type BetInput struct {
	PlayerID       string `json:"playerId"`
	Amount         int    `json:"amount"`
	BettingRoundID string `json:"bettingRoundId"`
}

type BettingRound struct {
	ID                 string   `json:"id"`
	FoldedPlayerIds    []string `json:"foldedPlayerIds"`
	Bets               []*Bet   `json:"bets"`
	CurrentPlayerID    string   `json:"currentPlayerId"`
	LastRaisedPlayerID string   `json:"lastRaisedPlayerId"`
}

type Game struct {
	ID                   string           `json:"id"`
	Players              []*Player        `json:"players"`
	QuestionRounds       []*QuestionRound `json:"questionRounds"`
	CurrentQuestionRound int              `json:"currentQuestionRound"`
	DealerID             string           `json:"dealerId"`
}

type Guess struct {
	Guess    float64 `json:"guess"`
	PlayerID string  `json:"playerId"`
}

type GuessInput struct {
	Guess           float64 `json:"guess"`
	PlayerID        string  `json:"playerId"`
	QuestionRoundID string  `json:"questionRoundId"`
}

type Hint struct {
	Hint string `json:"hint"`
}

type Player struct {
	ID    string `json:"id"`
	Money int    `json:"money"`
}

type Question struct {
	ID       string  `json:"id"`
	Question string  `json:"question"`
	Answer   float64 `json:"answer"`
	Hints    []*Hint `json:"hints"`
}

type QuestionRound struct {
	ID            string          `json:"id"`
	Question      *Question       `json:"question"`
	Guesses       []*Guess        `json:"guesses"`
	BettingRounds []*BettingRound `json:"bettingRounds"`
}
