// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Game struct {
	ID      string    `json:"id"`
	Players []*Player `json:"players"`
}

type NewPlayer struct {
	Name string `json:"name"`
}

type Player struct {
	ID             string  `json:"id"`
	Name           string  `json:"name"`
	RemainingMoney float64 `json:"remaining_money"`
}
